import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="min-h-screen px-2 flex flex-col justify-center align-center h-screen">
      <Head>
        <title>Place List - Best places to visit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-20 flex-1 flex flex-col justify-center items-center">
        <h1 className={styles.title}>Best places to visit</h1>

        <button>Join Placelist</button>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Warsaw</h2>
            <p>Poland</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>New York City</h2>
            <p>United States</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>London</h2>
            <p>United Kingdom</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Zagreb</h2>
            <p>Croatia</p>
          </a>
        </div>
      </main>

      <footer className="w-full py-8 border-t border-gray-200 flex justify-center align-center">
        <a href="#">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" width={36} height={36} />
          </span>
        </a>
      </footer>
    </div>
  );
}
