import { Place } from '.prisma/client';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import * as React from 'react';
import { useQuery } from 'react-query';
import { signIn, signOut, useSession } from 'next-auth/client';

type Error = {
  message?: string;
};

export default function Home() {
  const [session, loading] = useSession();
  const {
    isLoading,
    error,
    data: places,
  } = useQuery<Place[], Error>('places', () =>
    fetch('/api/places').then((res) => res.json().then((data) => data.places))
  );

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (error) {
    return 'An error has occured: ' + error.message;
  }

  return (
    <div className="min-h-screen px-2 flex flex-col justify-center align-center h-screen">
      <Head>
        <title>Place List - Best places to visit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-20 flex-1 flex flex-col justify-center items-center">
        {session ? (
          <>
            <p>You are authenticated! Hello {session.user?.name || 'user'}</p>
            <button onClick={() => signOut()}>Sign out</button>
          </>
        ) : (
          <>
            <button onClick={() => signIn()}>Sign in</button>
          </>
        )}
        <h1 className="text-6xl">Best places to visit</h1>

        {/* TODO: Implement log in */}
        <Link href="/dashboard">
          <a className="py-2 px-4 bg-blue-400 text-white rounded mt-6 uppercase tracking-wider font-medium hover:bg-blue-500 active:bg-blue-500">
            Join Placelist
          </a>
        </Link>

        <div className="flex items-center justify-center flex-wrap mt-8 max-w-xl mx-auto">
          {places?.length === 0 && <p>No places found</p>}
          {places?.map((place) => (
            <a
              href="#"
              className="m-2 p-4 text-left no-underline border border-blue-100 rounded-lg w-1/2"
            >
              <h2>{place.city}</h2>
              <p>{place.country}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className="w-full py-4 border-t border-gray-200 flex justify-center align-center">
        <a href="#" className="flex items-center">
          Powered by{' '}
          <span className="ml-2">
            <Image src="/logo.svg" width={36} height={36} />
          </span>
        </a>
      </footer>
    </div>
  );
}
